import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { AddTodoForm } from "~/components/todo/form";
import { api } from "~/utils/api";

const Todo: NextPage = () => {
  const utils = api.useContext();
  const todos = api.todo.getAll.useQuery();
  const deleteTodo = api.todo.delete.useMutation({
    onSettled: () => {
      utils.todo.getAll.invalidate();
    },
  });

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-3xl">Todo</h1>
        <div className="flex w-4/5 flex-col gap-4">
          {todos.data?.map((todo) => (
            <div key={todo.id} className="flex w-full justify-between">
              <p>{todo.title}</p>
              <div className="flex w-44 justify-between">
                <button
                  onClick={() => deleteTodo.mutate({ id: todo.id })}
                  className="w-20 rounded-md bg-red-500 text-white"
                >
                  Delete
                </button>
                <Link
                  href={`/todos/${todo.id}`}
                  className="w-20 rounded-md bg-green-200 text-center text-black"
                >
                  Edit
                </Link>
              </div>
            </div>
          ))}
        </div>
        <AddTodoForm />
      </main>
    </>
  );
};

export default Todo;
